import { useEffect, useState } from 'react'
import { Area, AreaChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { PackageOpen, Pickaxe, ReceiptText, TrendingUp, WalletCards, ArrowUpRight, Activity, Handshake, Crown, Layers3 } from 'lucide-react'
import { api, number, soles } from '../lib/api'
import { WORKSPACE_UPDATED_EVENT } from '../lib/cloud'

import GoldPrice from '../components/GoldPrice'
import WeatherCard from '../components/WeatherCard'
import { Link } from 'react-router-dom'

type Data={ownerProduction?:{partnerShareAll:number;ownAll:number;totalAll:number;partnerShareMonth:number;ownMonth:number;totalMonth:number};cycle?:{startedAt:string|null;closedLots:number;historicalSacks:number};cards:any;daily:any[];byLabor:any[];laborProgress:any[];expensesByLabor:any[];categories:any[];activity:any[]}
export default function Dashboard(){const [data,setData]=useState<Data|null>(null);const [error,setError]=useState('');useEffect(()=>{let mounted=true;const load=()=>api<Data>('/dashboard').then(value=>{if(mounted){setData(value);setError('')}}).catch(e=>{if(mounted)setError(e.message)});const visible=()=>{if(document.visibilityState==='visible')void load()};void load();window.addEventListener(WORKSPACE_UPDATED_EVENT,load);window.addEventListener('focus',load);document.addEventListener('visibilitychange',visible);const timer=window.setInterval(()=>{if(document.visibilityState==='visible')void load()},15000);return()=>{mounted=false;window.removeEventListener(WORKSPACE_UPDATED_EVENT,load);window.removeEventListener('focus',load);document.removeEventListener('visibilitychange',visible);window.clearInterval(timer)}},[])
if(error)return <div className="alert error">{error}</div>;if(!data)return <div className="skeleton-grid">{[1,2,3,4,5,6].map(i=><div className="skeleton" key={i}/>)}</div>
const cards=[['Sacos hoy',number(data.cards.todaySacks),PackageOpen,'amber','Hoy'],['Producción del lote',`${number(data.cards.totalSacks)} sacos`,TrendingUp,'amber',`${number(data.cards.monthSacks)} este mes`],['Labores activas',number(data.cards.activeLabors),Pickaxe,'blue','Datos actualizados'],['Gastos acumulados',soles(data.cards.totalExpensesCents),ReceiptText,'red',`${soles(data.cards.monthExpensesCents)} este mes`],['Deudas pendientes · PEN',soles(data.cards.pendingCents),WalletCards,'red','Datos actualizados'],['Ingresos acumulados · PEN',soles(data.cards.totalSalesCents),ArrowUpRight,'green',`${soles(data.cards.monthSalesCents)} este mes`]] as const
const owner=data.ownerProduction||{partnerShareAll:0,ownAll:0,totalAll:0,partnerShareMonth:0,ownMonth:0,totalMonth:0}
const partnerLaborColors=['#5fa8ff','#72d6b0']
return <div className="dashboard"><section className="top-kpi-strip"><article><span>Ingresos</span><strong>{soles(data.cards.totalSalesCents)}</strong><small>{soles(data.cards.monthSalesCents)} este mes</small></article><article><span>Sacos del lote actual</span><strong>{number(data.cards.totalSacks)}</strong><small>{number(data.cards.monthSacks)} este mes</small></article><article><span>Gastos</span><strong>{soles(data.cards.totalExpensesCents)}</strong><small>{soles(data.cards.monthExpensesCents)} este mes</small></article><article><span>Labores activas</span><strong>{number(data.cards.activeLabors)}</strong><small>Operación actual</small></article></section><section className="dashboard-intro"><div><span className="eyebrow">VISIÓN GENERAL · EN TIEMPO REAL</span><h2>Buenos días, Omar.</h2><p>Todo lo importante de la mina, en una sola mirada.</p></div><Link className="primary" to="/modelo-3d">Explorar mina <ArrowUpRight size={18}/></Link></section><section className="dashboard-hero dashboard-hero-market"><GoldPrice/><WeatherCard/></section>
<section className="owner-production"><div className="owner-production-head"><div><span className="eyebrow">Lote actual · Lo que te pertenece</span><h2>Tus sacos, separados con claridad</h2></div><p>{data.cycle?.closedLots?`${data.cycle.closedLots} lotes anteriores guardados · `:''}El historial nunca se elimina.</p></div><div className="owner-production-grid">
  <article className="owner-share-card glass total"><div className="owner-share-icon"><Layers3/></div><div><span>Total que me pertenece</span><strong>{number(owner.totalAll)} <small>sacos</small></strong><p>{number(owner.totalMonth)} este mes · socios + labor propia</p></div></article>
  <article className="owner-share-card glass partner"><div className="owner-share-icon"><Handshake/></div><div><span>Mi parte de labores con socios</span><strong>{number(owner.partnerShareAll)} <small>sacos</small></strong><p>{number(owner.partnerShareMonth)} este mes · según el porcentaje de cada labor</p></div></article>
  <article className="owner-share-card glass own"><div className="owner-share-icon"><Crown/></div><div><span>Mi labor propia · 100%</span><strong>{number(owner.ownAll)} <small>sacos</small></strong><p>{number(owner.ownMonth)} este mes · sin división con socios</p></div></article>
</div></section><section className="stat-grid">{cards.map(([label,value,Icon,tone,note])=><article className={`stat glass ${tone}`} key={label}><div className="stat-icon"><Icon/></div><div><span>{label}</span><strong>{value}</strong></div><small>{note}</small></article>)}</section>
<div className="dashboard-section-heading"><div><span className="eyebrow">ANALÍTICA</span><h2>Rendimiento de la operación</h2></div><small>Desliza para explorar →</small></div><section className="dash-grid"><article className="panel glass chart-main"><div className="panel-head"><div><span className="eyebrow">Rendimiento</span><h2>Producción diaria</h2></div><span className="chip">Últimos 30 registros</span></div>{data.daily.length?<ResponsiveContainer width="100%" height={250}><AreaChart data={data.daily}><defs><linearGradient id="production" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#d8b5cf" stopOpacity={.4}/><stop offset="1" stopColor="#d8b5cf" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#ffffff10"/><XAxis dataKey="label" stroke="#9f939d" fontSize={11}/><YAxis stroke="#9f939d" fontSize={11}/><Tooltip contentStyle={{background:'#100d11',border:'1px solid #cdaac333',borderRadius:14}}/><Area type="monotone" dataKey="value" name="Sacos" stroke="#e2c4d9" strokeWidth={3} fill="url(#production)"/></AreaChart></ResponsiveContainer>:<Empty/>}</article>
<article className="panel glass labor-lines"><div className="panel-head"><div><span className="eyebrow">Avance comparativo</span><h2>Producción por labor</h2></div><span className="chip">Acumulado</span></div>{data.laborProgress?.length&&data.byLabor.some(x=>x.value>0)?<ResponsiveContainer width="100%" height={310}><LineChart data={data.laborProgress} margin={{top:8,right:10,left:-10,bottom:10}}><CartesianGrid strokeDasharray="3 3" stroke="#ffffff10"/><XAxis dataKey="label" stroke="#958b99" fontSize={10}/><YAxis stroke="#958b99" fontSize={10}/><Tooltip contentStyle={{background:'#120f15',border:'1px solid #ffffff35',borderRadius:14}}/><Legend wrapperStyle={{fontSize:10,paddingTop:8}}/>{data.byLabor.filter(x=>x.value>0).map((labor,i)=>{const color=labor.isOwn?'#c495b7':partnerLaborColors[i%partnerLaborColors.length];return <Line key={labor.label} type="monotone" dataKey={labor.label} name={labor.isOwn?`${labor.label} · Propia`:labor.label} stroke={color} strokeWidth={labor.isOwn?3.4:2.6} dot={{r:labor.isOwn?3.6:3,fill:'#0d0a0f',strokeWidth:2}} activeDot={{r:5}} connectNulls/>})}</LineChart></ResponsiveContainer>:<Empty/>}</article>
<article className="panel glass expense-chart"><div className="panel-head"><div><span className="eyebrow">Costos</span><h2>Gastos por categoría</h2></div></div>{data.categories.length?<div className="pie-wrap"><ResponsiveContainer width="100%" height={240}><PieChart><Pie data={data.categories} dataKey="value" nameKey="label" innerRadius={65} outerRadius={95} paddingAngle={4}>{data.categories.map((_,i)=><Cell key={i} fill={['#4f9cf9','#35c88a','#f4b740','#ef6a78','#9b7cf6','#21b8c7','#f08cc4','#ff8b55'][i%8]}/>)}</Pie><Tooltip contentStyle={{background:'#100d11',border:'1px solid #cdaac333',borderRadius:14}}/></PieChart></ResponsiveContainer><div className="legend">{data.categories.slice(0,5).map((x,i)=><span key={x.label}><i style={{background:['#4f9cf9','#35c88a','#f4b740','#ef6a78','#9b7cf6'][i%5]}}/>{x.label}<b>S/ {number(x.value)}</b></span>)}</div></div>:<Empty/>}</article>
<article className="panel glass activity-panel"><div className="panel-head"><div><span className="eyebrow">Trazabilidad</span><h2>Últimas actividades</h2></div><Activity/></div>{data.activity.length?<div className="activity-list">{data.activity.map(x=><div key={x.id}><i/><div><b>{labelAction(x.action)} · {x.entity}</b><span>{x.user_name||'Sistema'} · {new Date(x.created_at+'Z').toLocaleString('es-PE')}</span></div></div>)}</div>:<Empty/>}</article></section></div>}
function Empty(){return <div className="empty"><PackageOpen/><b>No hay registros todavía.</b><span>Los datos aparecerán cuando registres operaciones.</span></div>}
function labelAction(v:string){return ({CREATE:'Creación',UPDATE:'Modificación',DELETE:'Eliminación',DEACTIVATE:'Desactivación',LOGIN:'Acceso',LOGOUT:'Salida'} as any)[v]||v}
