import { useEffect, useState } from 'react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { PackageOpen, Pickaxe, ReceiptText, TrendingUp, WalletCards, ArrowUpRight, Activity } from 'lucide-react'
import { api, number, soles } from '../lib/api'

type Data={cards:any;daily:any[];byLabor:any[];expensesByLabor:any[];categories:any[];activity:any[]}
export default function Dashboard(){const [data,setData]=useState<Data|null>(null);const [error,setError]=useState('');useEffect(()=>{api<Data>('/dashboard').then(setData).catch(e=>setError(e.message))},[])
if(error)return <div className="alert error">{error}</div>;if(!data)return <div className="skeleton-grid">{[1,2,3,4,5,6].map(i=><div className="skeleton" key={i}/>)}</div>
const cards=[['Sacos hoy',number(data.cards.todaySacks),PackageOpen,'amber'],['Producción del mes',`${number(data.cards.monthSacks)} sacos`,TrendingUp,'green'],['Labores activas',number(data.cards.activeLabors),Pickaxe,'blue'],['Gastos del mes',soles(data.cards.monthExpensesCents),ReceiptText,'red'],['Pendiente por recuperar',soles(data.cards.pendingCents),WalletCards,'violet'],['Ventas del mes',soles(data.cards.monthSalesCents),ArrowUpRight,'cyan']] as const
return <div className="dashboard"><section className="stat-grid">{cards.map(([label,value,Icon,tone])=><article className={`stat glass ${tone}`} key={label}><div className="stat-icon"><Icon/></div><div><span>{label}</span><strong>{value}</strong></div><small>Datos actualizados</small></article>)}</section>
<section className="dash-grid"><article className="panel glass chart-main"><div className="panel-head"><div><span className="eyebrow">Rendimiento</span><h2>Producción diaria</h2></div><span className="chip">Últimos 30 registros</span></div>{data.daily.length?<ResponsiveContainer width="100%" height={290}><AreaChart data={data.daily}><defs><linearGradient id="production" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#f7bd3b" stopOpacity={.5}/><stop offset="1" stopColor="#f7bd3b" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#ffffff10"/><XAxis dataKey="label" stroke="#82908a" fontSize={11}/><YAxis stroke="#82908a" fontSize={11}/><Tooltip contentStyle={{background:'#111714',border:'1px solid #ffffff20',borderRadius:14}}/><Area type="monotone" dataKey="value" name="Sacos" stroke="#f7bd3b" strokeWidth={3} fill="url(#production)"/></AreaChart></ResponsiveContainer>:<Empty/>}</article>
<article className="panel glass"><div className="panel-head"><div><span className="eyebrow">Distribución</span><h2>Producción por labor</h2></div></div>{data.byLabor.some(x=>x.value>0)?<ResponsiveContainer width="100%" height={290}><BarChart data={data.byLabor} layout="vertical"><CartesianGrid strokeDasharray="3 3" stroke="#ffffff10"/><XAxis type="number" stroke="#82908a"/><YAxis type="category" dataKey="label" width={90} stroke="#82908a" fontSize={11}/><Tooltip contentStyle={{background:'#111714',border:'1px solid #ffffff20',borderRadius:14}}/><Bar dataKey="value" name="Sacos" fill="#68d391" radius={[0,8,8,0]}/></BarChart></ResponsiveContainer>:<Empty/>}</article>
<article className="panel glass"><div className="panel-head"><div><span className="eyebrow">Costos</span><h2>Gastos por categoría</h2></div></div>{data.categories.length?<div className="pie-wrap"><ResponsiveContainer width="100%" height={240}><PieChart><Pie data={data.categories} dataKey="value" nameKey="label" innerRadius={65} outerRadius={95} paddingAngle={4}>{data.categories.map((_,i)=><Cell key={i} fill={['#f7bd3b','#68d391','#57a8ff','#f07474','#b18cff','#4ed9d0'][i%6]}/>)}</Pie><Tooltip contentStyle={{background:'#111714',border:'1px solid #ffffff20',borderRadius:14}}/></PieChart></ResponsiveContainer><div className="legend">{data.categories.slice(0,5).map((x,i)=><span key={x.label}><i style={{background:['#f7bd3b','#68d391','#57a8ff','#f07474','#b18cff'][i%5]}}/>{x.label}<b>S/ {number(x.value)}</b></span>)}</div></div>:<Empty/>}</article>
<article className="panel glass activity-panel"><div className="panel-head"><div><span className="eyebrow">Trazabilidad</span><h2>Últimas actividades</h2></div><Activity/></div>{data.activity.length?<div className="activity-list">{data.activity.map(x=><div key={x.id}><i/><div><b>{labelAction(x.action)} · {x.entity}</b><span>{x.user_name||'Sistema'} · {new Date(x.created_at+'Z').toLocaleString('es-PE')}</span></div></div>)}</div>:<Empty/>}</article></section></div>}
function Empty(){return <div className="empty"><PackageOpen/><b>No hay registros todavía.</b><span>Los datos aparecerán cuando registres operaciones.</span></div>}
function labelAction(v:string){return ({CREATE:'Creación',UPDATE:'Modificación',DELETE:'Eliminación',DEACTIVATE:'Desactivación',LOGIN:'Acceso',LOGOUT:'Salida'} as any)[v]||v}
