import {useEffect,useState,type FormEvent} from 'react'
import {Plus,HandCoins,UserRound} from 'lucide-react'
import {api,currencyMoney,today} from '../lib/api'
import {readAttachment} from '../lib/media'
import PhotoPicker from '../components/PhotoPicker'
import Modal from '../components/Modal'
type Debt=Record<string,any>
export default function Debts(){
  const [rows,setRows]=useState<Debt[]>([]),[edit,setEdit]=useState<Debt|null>(null),[payment,setPayment]=useState<Debt|null>(null),[photo,setPhoto]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const load=()=>api<Debt[]>('/debts').then(setRows).catch(e=>setError(e.message));useEffect(()=>{void load()},[])
  function open(row:Debt){setError('');setEdit(row);setPhoto(row.photo||'')}
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{const data=new FormData(e.currentTarget);const attachments=[...(edit?.attachments||[])];for(const file of data.getAll('attachments'))if(file instanceof File&&file.size)attachments.push({name:file.name,data:await readAttachment(file)});const body={...Object.fromEntries(data),photo,attachments};await api(edit?.id?`/debts/${edit.id}`:'/debts',{method:edit?.id?'PUT':'POST',body:JSON.stringify(body)});setEdit(null);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function pay(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{await api(`/debts/${payment!.id}/payments`,{method:'POST',body:new FormData(e.currentTarget)});setPayment(null);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <><div className="toolbar glass"><div><span className="eyebrow">Compromisos claros</span><h2>Préstamos y deudas</h2></div><button className="primary" onClick={()=>open({})}><Plus/> Registrar préstamo</button></div><div className="debt-summary">{['PEN','USD'].map(c=><div className="glass" key={c}><span className="eyebrow">Saldo pendiente · {c}</span><strong>{currencyMoney(rows.filter(x=>x.currency===c).reduce((sum,x)=>sum+x.pending_cents,0),c)}</strong></div>)}</div>{error&&!edit&&!payment&&<p className="alert error" role="alert">{error}</p>}<div className="debt-grid">{rows.map(row=><article className="panel glass debt-card" key={row.id}><div className="debt-person"><div className="profile-photo">{row.photo?<img src={row.photo} alt={row.name}/>:<UserRound/>}</div><div><h2>{row.name}</h2><small>Préstamo del {row.date}</small></div><span className={`badge ${row.status==='Pagado'?'active':'pending'}`}>{row.status}</span></div><div className="debt-values"><div><span>Prestado</span><b>{currencyMoney(row.amount_cents,row.currency)}</b></div><div><span>Devuelto</span><b className="income">{currencyMoney(row.paid_cents,row.currency)}</b></div><div><span>Pendiente</span><b>{currencyMoney(row.pending_cents,row.currency)}</b></div></div>{row.due_date&&<small>Devolución prevista: {row.due_date}</small>}{row.note&&<p>{row.note}</p>}<div className="attachments">{row.attachments?.map((x:Debt,i:number)=><a className="receipt-link" key={i} href={x.data} download={x.name}>Comprobante {i+1} ↗</a>)}</div><div className="actions"><button className="secondary" onClick={()=>open(row)}>Editar préstamo</button><button className="primary" disabled={row.pending_cents===0} onClick={()=>{setError('');setPayment(row)}}><HandCoins size={17}/> Registrar abono</button></div>{row.payments?.length>0&&<details className="debt-history"><summary>{row.payments.length} abonos registrados</summary>{row.payments.map((p:Debt)=><div key={p.id}><span>{p.date} · {p.note}</span><b className="income">{currencyMoney(p.amount_cents,row.currency)}</b>{p.receipt_data_url&&<a className="receipt-link" href={p.receipt_data_url} download={`abono-${p.id}`}>Comprobante</a>}</div>)}</details>}</article>)}</div>{!rows.length&&<div className="empty glass"><HandCoins/><b>Tus compromisos, en orden.</b><span>Registra el primer préstamo y lleva el control de cada devolución.</span></div>}
  {edit&&<Modal title={edit.id?'Editar préstamo':'Nuevo préstamo'} onClose={()=>!busy&&setEdit(null)}><form className="form-grid" onSubmit={save}><PhotoPicker value={photo} onChange={setPhoto} label="Foto de la persona"/><label>Nombre<input name="name" required defaultValue={edit.name}/></label><label>Fecha del préstamo<input name="date" type="date" required defaultValue={edit.date||today()}/></label><label>Monto prestado<input name="amount" type="number" min="0.01" step="0.01" required defaultValue={edit.amount_cents?edit.amount_cents/100:''}/></label><label>Moneda<select name="currency" defaultValue={edit.currency||'PEN'}><option value="PEN">Soles · PEN</option><option value="USD">Dólares · USD</option></select></label><label>Devolución prevista<input name="due_date" type="date" defaultValue={edit.due_date}/></label><label>Adjuntar comprobantes<input name="attachments" type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf"/><small>Las fotos se comprimen; PDF hasta 1 MB.</small></label><label className="span-2">Motivo u observación<textarea name="note" defaultValue={edit.note}/></label>{error&&<p className="alert error span-2" role="alert">{error}</p>}<button className="primary span-2" disabled={busy}>{busy?'Guardando…':'Guardar préstamo'}</button></form></Modal>}
  {payment&&<Modal title={`Abono a ${payment.name}`} onClose={()=>!busy&&setPayment(null)}><form className="form-grid" onSubmit={pay}><p className="span-2">Pendiente: {currencyMoney(payment.pending_cents,payment.currency)}</p><label>Fecha<input name="date" type="date" defaultValue={today()} required/></label><label>Monto ({payment.currency})<input name="amount" type="number" min="0.01" step="0.01" max={payment.pending_cents/100} required/></label><label className="span-2">Comprobante<input name="receipt" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"/></label><label className="span-2">Observación<textarea name="note"/></label>{error&&<p className="alert error span-2" role="alert">{error}</p>}<button className="primary span-2" disabled={busy}>{busy?'Guardando…':'Guardar abono'}</button></form></Modal>}</>
}
