import { useEffect, useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { Plus, MapPin, UserRound, Package, ReceiptText, ArrowUpRight, Search } from 'lucide-react'
import { api, number, soles } from '../lib/api'
import Modal from '../components/Modal'

export type Labor={id:number;name:string;code?:string;level?:string;location?:string;description?:string;status:string;partner_name:string;mine_percent:number;partner_percent:number;production_total:number;production_month:number;expenses_cents:number;last_activity:string}
export default function Labors(){const [items,setItems]=useState<Labor[]>([]);const [open,setOpen]=useState(false);const [search,setSearch]=useState('');const [error,setError]=useState('');const load=()=>api<Labor[]>('/labors').then(setItems).catch(e=>setError(e.message));useEffect(()=>{void load()},[])
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));try{await api('/labors',{method:'POST',body:JSON.stringify(data)});setOpen(false);load()}catch(e){setError((e as Error).message)}}
const filtered=items.filter(x=>`${x.name} ${x.partner_name} ${x.code||''}`.toLowerCase().includes(search.toLowerCase()))
return <><div className="toolbar glass"><label className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar labor o socio…"/></label><button className="primary" onClick={()=>setOpen(true)}><Plus/> Nueva labor</button></div>{error&&<div className="alert error">{error}</div>}
<section className="labor-grid">{filtered.map(l=><article className="labor-card glass" key={l.id}><div className="labor-top"><div className="labor-symbol"><span>{l.name.slice(0,2).toUpperCase()}</span></div><span className={`badge ${l.status}`}>{l.status==='active'?'Activa':'Inactiva'}</span></div><h2>{l.name}</h2><div className="labor-meta"><span><UserRound/> {l.partner_name}</span><span><MapPin/> {l.level||l.location||'Sin ubicación'}</span></div><div className="labor-stats"><div><Package/><span>Producción total</span><b>{number(l.production_total)} sacos</b></div><div><ReceiptText/><span>Gastos acumulados</span><b>{soles(l.expenses_cents)}</b></div></div><div className="split"><span>Mina <b>{l.mine_percent}%</b></span><i><em style={{width:`${l.mine_percent}%`}}/></i><span>Socio <b>{l.partner_percent}%</b></span></div><Link to={`/labores/${l.id}`}>Abrir labor <ArrowUpRight/></Link></article>)}{!filtered.length&&<div className="empty wide"><PickEmpty/><b>No hay labores todavía.</b><span>Crea la primera labor y asígnale un único socio responsable.</span></div>}</section>
{open&&<Modal title="Nueva labor" onClose={()=>setOpen(false)}><form className="form-grid" onSubmit={submit}><label>Nombre de labor<input name="name" required placeholder="Ej. Labor Arecio"/></label><label>Socio responsable<input name="partnerName" required placeholder="Nombre del socio"/></label><label>Código<input name="code" placeholder="LAB-001"/></label><label>Nivel<input name="level" placeholder="Nivel 420"/></label><label>Ubicación<input name="location" placeholder="Sector norte"/></label><label>Estado<select name="status"><option value="active">Activa</option><option value="inactive">Inactiva</option></select></label><label>Porcentaje Mina<input name="minePercent" type="number" min="0" max="100" defaultValue="50" required/></label><label>Porcentaje Socio<input name="partnerPercent" type="number" min="0" max="100" defaultValue="50" required/></label><label className="span-2">Descripción<textarea name="description" rows={3}/></label><div className="form-actions span-2"><button type="button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary">Guardar labor</button></div></form></Modal>}</>}
function PickEmpty(){return <div className="labor-symbol"><span>+</span></div>}
