import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, UserRound, Package, ReceiptText, Scale, BadgeDollarSign } from 'lucide-react'
import { api, number, soles } from '../lib/api'
import type { Labor } from './Labors'

export default function LaborDetail(){const {id}=useParams();const [labor,setLabor]=useState<Labor>();const [production,setProduction]=useState<any[]>([]);const [expenses,setExpenses]=useState<any[]>([]);const [liqs,setLiqs]=useState<any[]>([]);const [sales,setSales]=useState<any[]>([]);useEffect(()=>{Promise.all([api<Labor[]>('/labors'),api<any[]>(`/production?laborId=${id}`),api<any[]>(`/expenses?laborId=${id}`),api<any[]>(`/liquidations?laborId=${id}`),api<any[]>(`/sales?laborId=${id}`)]).then(([ls,p,e,l,s])=>{setLabor(ls.find(x=>x.id===Number(id)));setProduction(p);setExpenses(e);setLiqs(l);setSales(s)})},[id]);if(!labor)return <div className="skeleton"/>
return <><Link className="back-link" to="/labores"><ArrowLeft/> Volver a labores</Link><section className="labor-hero glass"><div className="labor-symbol large"><span>{labor.name.slice(0,2).toUpperCase()}</span></div><div><span className="eyebrow">Perfil de labor</span><h2>{labor.name}</h2><p><UserRound/> Socio responsable: <b>{labor.partner_name}</b></p></div><div className="split-card"><span>Distribución vigente</span><b>{labor.mine_percent}% <i>Mina</i> / {labor.partner_percent}% <i>Socio</i></b><small>Los registros históricos conservan el porcentaje aplicado.</small></div></section><section className="detail-grid"><Mini title="Producción" icon={<Package/>} value={`${number(production.reduce((a,x)=>a+x.sacks,0))} sacos`} link="/produccion"/><Mini title="Gastos" icon={<ReceiptText/>} value={soles(expenses.reduce((a,x)=>a+x.amount_cents,0))} link="/gastos"/><Mini title="Liquidaciones" icon={<Scale/>} value={`${liqs.length} registros`} link="/liquidaciones"/><Mini title="Ventas" icon={<BadgeDollarSign/>} value={`S/ ${number(sales.reduce((a,x)=>a+x.total,0))}`} link="/ventas"/></section><section className="panel glass"><div className="panel-head"><div><span className="eyebrow">Actividad</span><h2>Última producción</h2></div></div>{production.length?<div className="table-scroll"><table><thead><tr><th>Fecha</th><th>Sacos</th><th>Mina</th><th>Socio</th></tr></thead><tbody>{production.slice(0,8).map(x=><tr key={x.id}><td>{x.date}</td><td>{x.sacks}</td><td>{x.mine_sacks}</td><td>{x.partner_sacks}</td></tr>)}</tbody></table></div>:<div className="empty"><b>No hay registros todavía.</b></div>}</section></>}
function Mini({title,icon,value,link}:{title:string;icon:any;value:string;link:string}){return <Link className="mini-card glass" to={link}><div>{icon}<span>{title}</span></div><b>{value}</b></Link>}
