import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Plus, Search, SlidersHorizontal, FileImage, Trash2, PackageOpen } from 'lucide-react'
import { api, number, soles, timeNow, today } from '../lib/api'
import Modal from '../components/Modal'
import TrendCharts from '../components/TrendCharts'
import type { Labor } from './Labors'

type PageType='production'|'expenses'
const info={production:{title:'Registro de producción',button:'Registrar producción'},expenses:{title:'Nuevo gasto',button:'Registrar gasto'}}
export default function RecordsPage({type}:{type:PageType}){const [items,setItems]=useState<any[]>([]);const [labors,setLabors]=useState<Labor[]>([]);const [laborId,setLaborId]=useState('0');const [search,setSearch]=useState('');const [open,setOpen]=useState(false);const [error,setError]=useState('');const endpoint=`/${type}`
const load=()=>Promise.all([api<any[]>(`${endpoint}?laborId=${laborId}`),api<Labor[]>('/labors')]).then(([a,b])=>{setItems(a);setLabors(b)}).catch(e=>setError(e.message));useEffect(()=>{void load()},[laborId,type])
const filtered=useMemo(()=>items.filter(x=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase())),[items,search])
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const form=e.currentTarget;const data=new FormData(form);try{await api(endpoint,{method:'POST',body:data});setOpen(false);form.reset();load()}catch(e){setError((e as Error).message)}}
async function remove(id:number){if(!confirm('¿Desactivar este registro? Quedará guardado en el historial.'))return;try{await api(`${endpoint}/${id}`,{method:'DELETE'});load()}catch(e){setError((e as Error).message)}}
return <><div className="toolbar glass"><div className="toolbar-left"><label className="search"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar en registros…"/></label><label className="filter"><SlidersHorizontal/><select value={laborId} onChange={e=>setLaborId(e.target.value)}><option value="0">Todas las labores</option>{labors.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label></div><button className="primary" onClick={()=>setOpen(true)} disabled={!labors.length}><Plus/> {info[type].button}</button></div>{error&&<div className="alert error">{error}</div>}
<TrendCharts type={type} items={filtered}/>
<section className="panel glass table-panel"><div className="panel-head"><div><span className="eyebrow">Datos sincronizados</span><h2>{pageHeading(type)}</h2></div><span className="chip">{filtered.length} registros</span></div>{filtered.length?<div className="table-scroll"><table><thead><tr>{headers(type).map(h=><th key={h}>{h}</th>)}<th>Acciones</th></tr></thead><tbody>{filtered.map(x=><tr key={x.id}>{cells(type,x).map((c,i)=><td key={i}>{c}</td>)}<td><div className="row-actions">{x.receipt_data_url&&<a title="Ver comprobante" target="_blank" rel="noreferrer" href={x.receipt_data_url}><FileImage/></a>}<button title="Eliminar" onClick={()=>remove(x.id)}><Trash2/></button></div></td></tr>)}</tbody></table></div>:<div className="empty"><PackageOpen/><b>No hay registros todavía.</b><span>Usa el botón superior para registrar la primera operación.</span></div>}</section>
{open&&<Modal title={info[type].title} onClose={()=>setOpen(false)}><form className="form-grid" onSubmit={submit} encType="multipart/form-data"><LaborSelect labors={labors}/><DynamicFields type={type}/><div className="form-actions span-2"><button type="button" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary">{info[type].button}</button></div></form></Modal>}</>}

function LaborSelect({labors}:{labors:Labor[]}){return <label className="span-2">Labor<select name="laborId" required defaultValue=""><option value="" disabled>Selecciona una labor</option>{labors.filter(l=>l.status==='active').map(l=><option key={l.id} value={l.id}>{l.name} — {l.partner_name}</option>)}</select></label>}
function DynamicFields({type}:{type:PageType}){if(type==='production')return <><label>Fecha<input name="date" type="date" defaultValue={today()} required/></label><label>Cantidad de sacos<input name="sacks" type="number" min="0.01" step="0.01" required/></label><label className="span-2">Observación<textarea name="note" rows={3}/></label></>
return <><label>Nombre del gasto<input name="name" required placeholder="Ej. Pago a trabajadores"/></label><label>Monto (S/)<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Fecha<input name="expenseDate" type="date" defaultValue={today()} required/></label><label>Hora<input name="expenseTime" type="time" defaultValue={timeNow()} required/></label><label>Categoría<select name="category">{['Trabajadores','Coca','Transporte','Pasajes','Gasolina','Alimentación','Herramientas','Materiales','Otros'].map(x=><option key={x}>{x}</option>)}</select></label><label>Método de pago<select name="paymentMethod">{['Efectivo','Yape','Plin','Transferencia','Otro'].map(x=><option key={x}>{x}</option>)}</select></label><label className="span-2">Descripción<textarea name="description" rows={2}/></label><label className="span-2">Comprobante<input name="receipt" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"/><small>JPG, PNG, WebP o PDF · máximo 1 MB</small></label><label className="span-2">Observación<textarea name="observation" rows={2}/></label></>}

function pageHeading(t:PageType){return t==='production'?'Producción diaria':'Gastos registrados'}
function headers(t:PageType){return t==='production'?['Fecha','Labor','Sacos','Mina','Socio','Observación']:['Fecha','Labor','Gasto','Categoría','Monto','Parte socio','Método']}
function cells(t:PageType,x:any):any[]{if(t==='production')return [x.date,x.labor_name,<span className="sack-value">{number(x.sacks)}</span>,<span className="sack-value">{number(x.mine_sacks)}</span>,<span className="sack-value">{number(x.partner_sacks)}</span>,x.note||'—'];return [x.expense_date,x.labor_name,x.name,<span className="badge neutral">{x.category}</span>,<span className="expense">{soles(x.amount_cents)}</span>,<span className="expense">S/ {number(x.partner_share)}</span>,x.payment_method]}
