import {useEffect,useState,type FormEvent} from 'react'
import {Plus} from 'lucide-react'
import {api,currencyMoney,number,today,timeNow} from '../lib/api'
import Modal from '../components/Modal'
import TrendCharts from '../components/TrendCharts'
import type {Labor} from './Labors'
export default function Sales(){
  const [rows,setRows]=useState<any[]>([]),[labors,setLabors]=useState<Labor[]>([]),[open,setOpen]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[currency,setCurrency]=useState('PEN'),[labor,setLabor]=useState('0'),[saleLabor,setSaleLabor]=useState('')
  const load=()=>Promise.all([api<any[]>('/sales'),api<Labor[]>('/labors')]).then(([a,b])=>{setRows(a);setLabors(b)}).catch(e=>setError(e.message));useEffect(()=>{void load()},[])
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');try{await api('/sales',{method:'POST',body:new FormData(e.currentTarget)});setOpen(false);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const filtered=rows.filter(x=>(x.currency||'PEN')===currency&&(!Number(labor)||x.labor_id===Number(labor)))
  const selected=labors.find(x=>String(x.id)===saleLabor)||labors.find(x=>x.status==='active')
  return <><div className="toolbar glass"><div className="toolbar-left"><label>Moneda<select value={currency} onChange={e=>setCurrency(e.target.value)}><option value="PEN">Soles · PEN</option><option value="USD">Dólares · USD</option></select></label><label>Labor<select value={labor} onChange={e=>setLabor(e.target.value)}><option value="0">Todas las labores</option>{labors.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label></div><button className="primary" disabled={!labors.length} onClick={()=>{setError('');setSaleLabor(String(labors.find(x=>x.status==='active')?.id||''));setOpen(true)}}><Plus/> Registrar venta</button></div>{error&&!open&&<p className="alert error">{error}</p>}<TrendCharts type="sales" items={filtered} currency={currency}/><section className="panel glass"><div className="panel-head"><div><span className="eyebrow">Comercialización</span><h2>Ventas de mineral</h2></div><span className="chip">{filtered.length} operaciones</span></div><div className="table-scroll"><table><thead><tr>{['Fecha / hora','Comprador','Labor','Sacos vendidos','Peso','Ley','Ingreso recibido','Ganancia neta','Comprobante'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{filtered.map(x=><tr key={x.id}><td>{x.sale_date}<br/><small>{x.sale_time}</small></td><td>{x.buyer}</td><td>{x.labor_name}</td><td>{x.sold_sacks!=null?number(x.sold_sacks):'Venta histórica'}</td><td>{x.weight!=null?`${number(x.weight)} ${x.weight_unit}`:`${number(x.sacks)} sacos (histórico)`}</td><td>{x.grade!=null?`${number(x.grade)} ${x.grade_unit}`:'Sin registrar'}</td><td className="income">{currencyMoney(x.total_cents,x.currency||'PEN')}</td><td className={x.profit_cents>=0?'income':''}>{x.profit_cents!=null?currencyMoney(x.profit_cents,x.currency):'Costos no registrados'}</td><td>{x.receipt_data_url&&<a className="receipt-link" href={x.receipt_data_url} download={`venta-${x.id}`}>Descargar ↗</a>}</td></tr>)}</tbody></table></div>{!filtered.length&&<div className="empty"><b>Registra tu primera venta.</b><span>Sacos, peso, ley e importe recibido en una sola operación.</span></div>}</section>
  {open&&<Modal title="Nueva venta de mineral" onClose={()=>!busy&&setOpen(false)}><form className="form-grid" onSubmit={save}><label>Labor<select name="laborId" required value={saleLabor} onChange={e=>setSaleLabor(e.target.value)}>{labors.filter(l=>l.status==='active').map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><small>{number(selected?.available_sacks||0)} sacos disponibles</small></label><label>Comprador<input name="buyer" required/></label><label>Fecha<input name="date" type="date" required defaultValue={today()}/></label><label>Hora<input name="time" type="time" required defaultValue={timeNow()}/></label><label>Sacos vendidos<input name="soldSacks" type="number" min="0.01" max={selected?.available_sacks||undefined} step="0.01" required/><small>Se descontarán únicamente del inventario disponible.</small></label><label>Peso total<input name="weight" type="number" min="0.001" step="0.001" required/></label><label>Unidad de peso<select name="weight_unit"><option value="kg">Kilogramos</option><option value="t">Toneladas</option></select></label><label>Ley del mineral<input name="grade" type="number" min="0" step="0.0001" required/></label><label>Unidad de ley<select name="grade_unit"><option value="g/t">Gramos por tonelada (g/t)</option><option value="oz/t">Onzas por tonelada (oz/t)</option><option value="%">Porcentaje (%)</option></select></label><label>Importe recibido<input name="received" type="number" min="0" step="0.01" required className="income"/></label><label>Moneda<select name="currency" defaultValue={currency}><option value="PEN">Soles · PEN</option><option value="USD">Dólares · USD</option></select></label><label>Costos asociados (opcional)<input name="costs" type="number" min="0" step="0.01"/><small>Se restan del ingreso, pero el historial del dinero nunca se borra.</small></label><label>Comprobante<input name="receipt" type="file" accept="image/jpeg,image/png,image/webp,application/pdf"/></label><label className="span-2">Observaciones<textarea name="observation"/></label>{error&&<p className="alert error span-2" role="alert">{error}</p>}<button className="primary span-2" disabled={busy||!Number(selected?.available_sacks)}>{busy?'Guardando…':'Guardar venta y descontar sacos'}</button></form></Modal>}</>
}
