import {useState} from 'react'
import {Download,Upload,ShieldCheck,RefreshCw} from 'lucide-react'
import {api,today} from '../lib/api'
import {downloadFile} from '../lib/media'
import type {User} from '../App'
export default function Settings({user}:{user:User}){
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 async function backup(){setBusy(true);try{const db=await api('/backup');downloadFile('mina-respaldo-'+today()+'.json',new Blob([JSON.stringify(db)],{type:'application/json'}));setMessage('Respaldo descargado con fotografías, comprobantes e historial.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function sync(){setBusy(true);try{await api('/sync',{method:'POST'});setMessage('Sincronización comprobada. Tus datos están guardados en Supabase.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function restore(file?:File){if(!file)return;setBusy(true);try{if(file.size>40000000)throw new Error('El respaldo supera los 40 MB.');const db=JSON.parse(await file.text());if(!confirm('Se reemplazarán los datos actuales por este respaldo. Descarga primero una copia actual. ¿Continuar?'))return;await api('/backup',{method:'POST',body:JSON.stringify(db)});setMessage('Respaldo restaurado. Actualiza las demás pantallas para ver los datos.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 async function legacy(){try{const raw=localStorage.getItem('mina-omar-miranda-db-v1');if(!raw)throw new Error('No hay datos de la versión anterior en este navegador.');const db=JSON.parse(raw);db.users=[];db.debts=db.debts||[];downloadFile('mina-datos-anteriores.json',new Blob([JSON.stringify(db)],{type:'application/json'}));setMessage('Copia anterior exportada sin contraseñas. Puedes importarla si tu espacio nuevo está vacío.')}catch(e){setMessage((e as Error).message)}}
 return <div className="settings-grid"><article className="panel glass"><div className="panel-head"><div><span className="eyebrow">Tu espacio privado</span><h2>Cuenta autorizada</h2></div><ShieldCheck/></div><p>{user.email}</p><p>Los datos y fotografías se guardan en Supabase y se consultan desde los dispositivos donde inicies sesión. El código y el modelo 3D de GitHub Pages siguen siendo públicos.</p><button className="secondary" disabled={busy} onClick={sync}><RefreshCw size={18}/> Comprobar sincronización</button><small>El plan gratuito puede pausar el servicio tras un periodo de inactividad. No se han contratado planes de pago.</small>{message&&<p className="alert" role="status">{message}</p>}</article><article className="panel glass"><span className="eyebrow">Siempre contigo</span><h2>Respaldos completos</h2><p>Conserva una copia de registros, fotografías, comprobantes e historial.</p><div className="backup-actions"><button className="primary" disabled={busy} onClick={backup}><Download size={18}/> Exportar respaldo</button><label className="secondary"><Upload size={18}/> Importar respaldo<input type="file" accept=".json,application/json" hidden disabled={busy} onChange={e=>{void restore(e.target.files?.[0]);e.target.value=''}}/></label><button className="secondary" onClick={legacy}>Exportar datos de la versión anterior</button></div></article></div>
}
