import { useEffect,useState } from 'react'
import { RefreshCw, Sparkles } from 'lucide-react'
type Quote={price:number;updatedAt:string;currency:string;symbol:string}
const cacheKey='mina-gold-quote-v1'
export default function GoldPrice(){
  const [quote,setQuote]=useState<Quote|null>(()=>{try{const q=JSON.parse(localStorage.getItem(cacheKey)||'null');return q&&Number.isFinite(q.price)?q:null}catch{return null}});const [failed,setFailed]=useState(false);const [busy,setBusy]=useState(false);const [tick,setTick]=useState(Date.now());const [refresh,setRefresh]=useState(0)
  useEffect(()=>{let controller:AbortController|null=null;let active=true;let fetching=false;async function load(){if(fetching)return;fetching=true;setBusy(true);controller=new AbortController();const current=controller;const timeout=setTimeout(()=>current.abort(),12000);try{const res=await fetch('https://api.gold-api.com/price/XAU',{signal:current.signal});if(!res.ok)throw new Error('Cotización no disponible');const q=await res.json();if(q.symbol!=='XAU'||!Number.isFinite(q.price)||q.price<=0||!Number.isFinite(Date.parse(q.updatedAt)))throw new Error('Cotización inválida');if(active){setQuote(q);setFailed(false);try{localStorage.setItem(cacheKey,JSON.stringify(q))}catch{}}}catch{if(active)setFailed(true)}finally{clearTimeout(timeout);fetching=false;if(active){setBusy(false);setTick(Date.now())}}}void load();const interval=setInterval(()=>{setTick(Date.now());if(!document.hidden)void load()},60000);return()=>{active=false;controller?.abort();clearInterval(interval)}},[refresh])
  const stale=failed||!quote||tick-Date.parse(quote.updatedAt)>180000
  return <article className="gold-card glass"><div className="gold-orbit" aria-hidden="true"><i/><i/><div>Au<span>79</span></div></div><div className="gold-content"><div className="panel-head"><span className="eyebrow"><Sparkles size={13}/> MERCADO DEL ORO</span><button className="icon-button" aria-label="Actualizar precio del oro" disabled={busy} onClick={()=>setRefresh(x=>x+1)}><RefreshCw size={17} className={busy?'spinning':''}/></button></div><span className="quote-status"><i className={stale?'stale':''}/>{stale?'Última cotización disponible':'Cotización actualizada'}</span><strong className="gold-price" key={quote?.price}>{quote?new Intl.NumberFormat('es-PE',{style:'currency',currency:'USD'}).format(quote.price):'—'}</strong><p>USD / onza troy · XAU</p><footer><a href="https://gold-api.com" target="_blank" rel="noreferrer">Gold API ↗</a><span>{quote?new Date(quote.updatedAt).toLocaleString('es-PE'):'Consultando mercado…'}</span></footer><small>{failed?'Sin conexión con la fuente. La cotización puede estar desactualizada.':'Consulta cada 60 s. Sin variación diaria disponible en esta fuente.'}</small></div></article>
}
