import { useState } from 'react'
import { NavLink, Outlet, useLocation } from 'react-router-dom'
import { LayoutDashboard, Pickaxe, ChartNoAxesCombined, ReceiptText, HandCoins, Scale, BadgeDollarSign, Map, Box, FileChartColumn, History, Settings, LogOut, Menu, X, Bell, Search, Mountain } from 'lucide-react'
import { api } from '../lib/api'
import type { User } from '../App'

const nav=[['/','Dashboard',LayoutDashboard],['/labores','Labores',Pickaxe],['/produccion','Producción',ChartNoAxesCombined],['/gastos','Gastos',ReceiptText],['/recuperacion','Recuperación',HandCoins],['/liquidaciones','Liquidaciones',Scale],['/ventas','Ventas',BadgeDollarSign],['/recorrido','Recorrido 2D',Map],['/modelo-3d','Modelo 3D',Box],['/reportes','Reportes',FileChartColumn],['/historial','Historial',History],['/configuracion','Configuración',Settings]] as const
const titles:Record<string,string>={'/':'Centro de control','/labores':'Labores mineras','/produccion':'Producción diaria','/gastos':'Gastos por labor','/recuperacion':'Recuperación de gastos','/liquidaciones':'Reparticiones y liquidaciones','/ventas':'Ventas','/recorrido':'Recorrido de la mina','/modelo-3d':'Modelo 3D','/reportes':'Reportes','/historial':'Historial y auditoría','/configuracion':'Configuración'}

export default function Layout({user,onLogout}:{user:User;onLogout:()=>void}){const [open,setOpen]=useState(false);const location=useLocation();const title=titles[location.pathname]||'Detalle de labor';async function logout(){await api('/auth/logout',{method:'POST'});onLogout()}
return <div className="app-shell"><aside className={open?'sidebar open':'sidebar'}><div className="logo"><div className="logo-icon"><Mountain/></div><div><b>MINA OMAR</b><span>MIRANDA</span></div><button className="mobile-close" onClick={()=>setOpen(false)}><X/></button></div><nav>{nav.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/'} onClick={()=>setOpen(false)}><Icon/><span>{label}</span></NavLink>)}</nav><div className="side-user"><div className="avatar">{user.name.slice(0,2).toUpperCase()}</div><div><b>{user.name}</b><span>{user.role}</span></div><button title="Cerrar sesión" onClick={logout}><LogOut/></button></div></aside>{open&&<button className="backdrop" onClick={()=>setOpen(false)}/>}<section className="main"><header><button className="menu-button" onClick={()=>setOpen(true)}><Menu/></button><div><span className="eyebrow">MINA OMAR MIRANDA</span><h1>{title}</h1></div><div className="header-tools"><button title="Buscar"><Search/></button><button title="Notificaciones"><Bell/><i/></button><div className="header-avatar">{user.name.slice(0,2).toUpperCase()}</div></div></header><div className="page"><Outlet/></div></section></div>}
